nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['http://localhost:5173'] # Ajusta al origen de tu frontend
    allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    expose_headers: []
    max_age: 3600
  
  paths:
    '^/':  # Se aplica a todas las rutas que empiecen con /
      allow_origin: ['http://localhost:5173']
      allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
      allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
      allow_credentials: true
