security:
  enable_authenticator_manager: true

  # Configuración del hasher de contraseñas
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # Proveedores de usuarios
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Firewalls de autenticación
  firewalls:
    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~
      # Usuarios activos
      user_checker: App\Security\UserChecker

  # Control de acceso
  access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/register, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
